/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_pages;
import javax.swing.*;
/**
 *
 * @author Angie
 */
public class dashBoard_page extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashBoard_page
     */
    public dashBoard_page() {
        initComponents();
    
      java.net.URL gifURL = getClass().getResource("/Images/Untitled design.gif");
    if (gifURL == null) {
        System.out.println("GIF NOT FOUND");
        return;
    }

    ImageIcon gifIcon = new ImageIcon(gifURL);

    GIF.setIcon(gifIcon);
    GIF.setOpaque(false); // 🔥 THIS IS THE KEY
    
    jPanel4.revalidate();
    jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        GIF = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(92, 21, 53));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(490, 0, 190, 180);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Velvet Cafe V1.1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 250, 38);

        jLabel2.setText("Additional System description");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 140, 14);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 744, 174));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(92, 21, 53));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GIF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design.gif"))); // NOI18N
        jPanel4.add(GIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 190, 180));

        jPanel2.add(jPanel4);
        jPanel4.setBounds(30, 20, 660, 280);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 744, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
