/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_pages;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Angie
 */
public class homePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bakcground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(760, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bakcground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bakcground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_image.png"))); // NOI18N
        getContentPane().add(Bakcground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bakcground;
    // End of variables declaration//GEN-END:variables
}
