/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;

/**
 *
 * @author Angie
 */
public class Landingform extends javax.swing.JFrame {

    /**
     * Creates new form Landingform
     */
    public Landingform() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        font1 = new javax.swing.JLabel();
        font2 = new javax.swing.JLabel();
        beans = new javax.swing.JLabel();
        leaf = new javax.swing.JLabel();
        font3 = new javax.swing.JLabel();
        sign_btn = sign_btn = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                // This makes the rounded edges smooth
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This tells the code: "Use whatever color is already set for this panel"
                g2.setColor(getBackground());

                // This only paints the rounded area
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);

                g2.dispose();
            }
        };
        // Crucial: Add this in your constructor to hide the "square" background
        sign_btn.setOpaque(false);
        sign = new javax.swing.JLabel();
        login_btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        start_btn = start_btn = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                // This makes the rounded edges smooth
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This tells the code: "Use whatever color is already set for this panel"
                g2.setColor(getBackground());

                // This only paints the rounded area
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);

                g2.dispose();
            }
        };
        // Crucial: Add this in your constructor to hide the "square" background
        start_btn.setOpaque(false);
        start = new javax.swing.JLabel();
        background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 50));

        font1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        font1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/font1.png"))); // NOI18N
        background.add(font1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, 40));

        font2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        font2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/font2.png"))); // NOI18N
        background.add(font2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 350, 120));

        beans.setBackground(new java.awt.Color(255, 255, 255));
        beans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/beans_design.png"))); // NOI18N
        beans.setOpaque(true);
        background.add(beans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 200));

        leaf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leaf-.png"))); // NOI18N
        background.add(leaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 110, 120));

        font3.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        font3.setForeground(new java.awt.Color(139, 94, 60));
        font3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        font3.setText("Sign up or Log in to manage your coffee shop");
        background.add(font3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 30));

        sign_btn.setBackground(new java.awt.Color(217, 155, 65));
        sign_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sign_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sign_btnMouseReleased(evt);
            }
        });
        sign_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sign.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        sign.setForeground(new java.awt.Color(255, 255, 255));
        sign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sign.setText("Sign up");
        sign_btn.add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 80, -1));

        background.add(sign_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 40));

        login_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 194, 178), 1, true));
        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                login_btnMouseReleased(evt);
            }
        });
        login_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(45, 45, 45));
        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 36, 21));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log in");
        login_btn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, -1, 30));

        background.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 110, 40));

        start_btn.setBackground(new java.awt.Color(217, 155, 65));
        start_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                start_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                start_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                start_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                start_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                start_btnMouseReleased(evt);
            }
        });
        start_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        start.setForeground(new java.awt.Color(240, 240, 240));
        start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start.setText("Get Started");
        start_btn.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 130, -1));

        background.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 40));

        background_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_image.png"))); // NOI18N
        background.add(background_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
     Loginform lm = new Loginform();
     lm.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_login_btnMouseClicked

    private void sign_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_btnMouseClicked
        Registrationform rm = new Registrationform();
        rm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sign_btnMouseClicked

    private void sign_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_btnMouseEntered
        sign_btn.setBackground(new Color(198, 135, 65));
        
    }//GEN-LAST:event_sign_btnMouseEntered

    private void sign_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_btnMouseExited
        sign_btn.setBackground(new Color(217,155,65));
    }//GEN-LAST:event_sign_btnMouseExited

    private void sign_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_btnMousePressed
        sign_btn.setBackground(new Color(170, 110, 50));
    }//GEN-LAST:event_sign_btnMousePressed

    private void sign_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_btnMouseReleased
       sign_btn.setBackground(new Color(217,155,65));
    }//GEN-LAST:event_sign_btnMouseReleased

    private void login_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseEntered
        login_btn.setBackground(new Color(230, 220, 205));
    }//GEN-LAST:event_login_btnMouseEntered

    private void login_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseExited
        login_btn.setBackground(new Color (240,240,240));
    }//GEN-LAST:event_login_btnMouseExited

    private void login_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMousePressed
       login_btn.setBackground(new Color(210, 200, 180));
       login_btn.setForeground(new Color (62, 39, 35));
    }//GEN-LAST:event_login_btnMousePressed

    private void login_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseReleased
         login_btn.setBackground(new Color (240,240,240));
          login_btn.setForeground(new Color (60,36,21));
    }//GEN-LAST:event_login_btnMouseReleased

    private void start_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMouseClicked
       
    }//GEN-LAST:event_start_btnMouseClicked

    private void start_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMouseEntered
           start_btn.setBackground(new Color(198, 135, 65));
    }//GEN-LAST:event_start_btnMouseEntered

    private void start_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMouseExited
       start_btn.setBackground(new Color(217,155,65));
    }//GEN-LAST:event_start_btnMouseExited

    private void start_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMousePressed
       start_btn.setBackground(new Color(170, 110, 50));
    }//GEN-LAST:event_start_btnMousePressed

    private void start_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMouseReleased
         start_btn.setBackground(new Color(217,155,65));
    }//GEN-LAST:event_start_btnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Landingform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel background_image;
    private javax.swing.JLabel beans;
    private javax.swing.JLabel font1;
    private javax.swing.JLabel font2;
    private javax.swing.JLabel font3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel leaf;
    private javax.swing.JPanel login_btn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel sign;
    private javax.swing.JPanel sign_btn;
    private javax.swing.JLabel start;
    private javax.swing.JPanel start_btn;
    // End of variables declaration//GEN-END:variables
}
