package main;
import java.awt.Color;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angie
 */
public class Landingform extends javax.swing.JFrame {

    /**
     * Creates new form Landingform
     */
    public Landingform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Headername = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        rightdesign = new javax.swing.JPanel();
        font1 = new javax.swing.JLabel();
        font2 = new javax.swing.JLabel();
        link = new javax.swing.JPanel();
        button = new javax.swing.JLabel();
        font3 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Body.setBackground(new java.awt.Color(204, 153, 0));
        Body.setPreferredSize(new java.awt.Dimension(760, 420));
        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(92, 21, 53));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Headername.setFont(new java.awt.Font("Kunstler Script", 2, 75)); // NOI18N
        Headername.setForeground(new java.awt.Color(204, 153, 0));
        Headername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Headername.setText("Velvet Café ");
        Header.add(Headername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee_logo_180x180-removebg-preview.png"))); // NOI18N
        logo.setText("jLabel3");
        Header.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 11, 94, 78));

        jPanel2.setBackground(new java.awt.Color(92, 21, 53));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(close)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        Header.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 20));

        jPanel3.setBackground(new java.awt.Color(92, 21, 53));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(minimize)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        Header.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 0, 40, 20));

        Body.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        rightdesign.setBackground(new java.awt.Color(255, 255, 153));
        rightdesign.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        font1.setFont(new java.awt.Font("Felix Titling", 2, 36)); // NOI18N
        font1.setForeground(new java.awt.Color(204, 153, 0));
        font1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        font1.setText("Welcome ");
        rightdesign.add(font1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, -1));

        font2.setFont(new java.awt.Font("Felix Titling", 2, 36)); // NOI18N
        font2.setForeground(new java.awt.Color(204, 153, 0));
        font2.setText("TO");
        rightdesign.add(font2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, -1));

        link.setBackground(new java.awt.Color(92, 21, 53));

        button.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 153));
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setText("Click here to continue");
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout linkLayout = new javax.swing.GroupLayout(link);
        link.setLayout(linkLayout);
        linkLayout.setHorizontalGroup(
            linkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        linkLayout.setVerticalGroup(
            linkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        rightdesign.add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, 40));

        font3.setFont(new java.awt.Font("Kunstler Script", 2, 73)); // NOI18N
        font3.setForeground(new java.awt.Color(204, 153, 0));
        font3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        font3.setText("Velvet Café ");
        rightdesign.add(font3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 280, -1));

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee_logo_180x180-removebg-preview.png"))); // NOI18N
        logo2.setText("jLabel3");
        rightdesign.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 94, 78));

        Body.add(rightdesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 300, 310));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Velvet Café.png"))); // NOI18N
        Body.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 310));

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 402));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
       Loginform lf = new Loginform();
       lf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_buttonMouseClicked

    
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
      button.setForeground(new Color(204,153,0));
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
      button.setForeground(new Color(255, 255, 153));
    }//GEN-LAST:event_buttonMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(new Color(10,10,10));
    }//GEN-LAST:event_closeMouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       jPanel2.setBackground(new Color(255, 5, 0));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
          jPanel2.setBackground(new Color(92, 21, 53
          ));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
       jPanel3.setBackground(new Color(92, 21, 53));
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landingform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Headername;
    private javax.swing.JLabel button;
    private javax.swing.JLabel close;
    private javax.swing.JLabel font1;
    private javax.swing.JLabel font2;
    private javax.swing.JLabel font3;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel link;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel rightdesign;
    // End of variables declaration//GEN-END:variables
}
