/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and  open the template in the editor.
 */
package main;
import config.DBcon;
import config.passUtil;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import admin.Admindashboard;
import User.Userdashboard;
import java.awt.Color;
/**
 *
 * @author Angie
 */
public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginform = loginform = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 10;
                int borderRadius = 30;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        loginform.setOpaque(false);
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        log_panel = log_panel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                // This makes the rounded edges smooth
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This tells the code: "Use whatever color is already set for this panel"
                g2.setColor(getBackground());

                // This only paints the rounded area
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);

                g2.dispose();
            }
        };
        // Crucial: Add this in your constructor to hide the "square" background
        log_panel.setOpaque(false);
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 60, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/font1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 200, 30));

        loginform.setBackground(new java.awt.Color(255, 255, 204));
        loginform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(255, 255, 204));
        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 217, 200)));
        loginform.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 40));

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 194, 178), 1, true));
        loginform.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 50, 22));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        loginform.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(92, 50, 22));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email Address");
        loginform.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        log_panel.setBackground(new java.awt.Color(217, 167, 60));
        log_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_panelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                log_panelMouseReleased(evt);
            }
        });
        log_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log in");
        log_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 20));

        loginform.add(log_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(92, 50, 22));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Log in");
        loginform.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(92, 50, 22));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Don't have an account?");
        loginform.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(217, 167, 60));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sign up here");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        loginform.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        getContentPane().add(loginform, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 340, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Registrationform rn = new Registrationform();
        rn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void log_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_panelMouseClicked
          String Email = email.getText().trim();
        String pass = passUtil.hashPassword(new String(password.getPassword()));

        if (Email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Type your User and Password.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

       DBcon con = new DBcon();
       String sql = "SELECT * FROM users WHERE email = ? AND password = ? AND u_status = ?";
       
       String account_Type = con.authenticate(sql, email.getText(), password.getText(), "Active");
       
       if(account_Type != null){
           
           JOptionPane.showMessageDialog(null, "Log in successful");
           if(account_Type.equals("Admin")){
               Admindashboard ad = new Admindashboard();
               ad.setVisible(true);
               this.dispose();
           }else if (account_Type.equals("User")){
               Userdashboard ud = new Userdashboard();
               ud.setVisible(true);
               this.dispose();
           }else{
               JOptionPane.showMessageDialog(null, "Invalid Account Type!");
               return;
           }
       }else{
           JOptionPane.showMessageDialog(null, "Invalid Credentials / Account Inactive!");
       }
    }//GEN-LAST:event_log_panelMouseClicked

    private void log_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_panelMouseEntered
       log_panel.setBackground(new Color(198, 135, 65));
    }//GEN-LAST:event_log_panelMouseEntered

    private void log_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_panelMouseExited
       log_panel.setBackground(new Color(217,167,60));
    }//GEN-LAST:event_log_panelMouseExited

    private void log_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_panelMousePressed
        log_panel.setBackground(new Color(170, 110, 50));
    }//GEN-LAST:event_log_panelMousePressed

    private void log_panelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_panelMouseReleased
       log_panel.setBackground(new Color(217,167,60));
    }//GEN-LAST:event_log_panelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel log_panel;
    private javax.swing.JPanel loginform;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
