/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import User.Userdashboard;
import admin.Admindashboard;
import config.DBcon;
import internal_pages.Users_page;
import java.awt.Color;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;

/**
 *
 * @author Lester
 */
public class Orders_form extends javax.swing.JFrame {

    /**
     * Creates new form Orders_page
     */
    public Orders_form() {
        initComponents();
        
          this.setBackground(new java.awt.Color(0, 0, 0, 0));
          p_spinner();
    }
    
    
    
       public void close() {
   
    this.dispose();

  
    String role = config.userSession.getInstance().getRole();

    if (role.equalsIgnoreCase("Admin")) {
        // Redirection for Admin
        Admindashboard adminDash = new Admindashboard();
        adminDash.setVisible(true);
        
      
        Users_page up = new Users_page();
        adminDash.contentPanel.add(up).setVisible(true);
        
    } else {
        // Redirection for regular Staff/User
        Userdashboard userDash = new Userdashboard();
        userDash.setVisible(true);
        
         Users_page up = new Users_page();
        userDash.contentPanel.add(up).setVisible(true);
         }
}
    
    
                  public String destination = "";
    File selectedFile;
    public String oldpath;
    public String path;
    
    
  int validateRegister() {
    // Only check the fields that actually exist in your form
    if (orderdate.getText().isEmpty() || amount.getText().isEmpty()) {
        return 0;
    }

    try {
        // Ensure the amount is a valid number (since DB type is REAL)
        Double.parseDouble(amount.getText());
        return 1;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Amount must be a valid number!");
        return 0;
    }
}
      
    public String action;
    
   public void p_spinner() {
    DBcon dbc = new DBcon();
    try {
        java.sql.ResultSet rs = dbc.getData("SELECT c_id FROM tbl_customers");
        
        // Use java.util.List and ArrayList to store the IDs
        java.util.List<Integer> idList = new java.util.ArrayList<>();

        while (rs.next()) {
            idList.add(rs.getInt("c_id"));
        }

        if (!idList.isEmpty()) {
            // SpinnerListModel handles the navigation through your specific IDs
            SpinnerListModel model = new SpinnerListModel(idList);
            cId.setModel(model);
        } else {
            JOptionPane.showMessageDialog(null, "No customers found in database.");
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error fetching IDs: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);
        st_label = new javax.swing.JLabel();
        orderdate = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        or_id = new javax.swing.JLabel();
        cId = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(166, 123, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A67B5B.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffe.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 60));

        jPanel1.setBackground(new java.awt.Color(253, 245, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(166, 123, 91));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 30));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 210, 50));

        orderdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        orderdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        orderdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderdateActionPerformed(evt);
            }
        });
        jPanel1.add(orderdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 240, 30));

        amount.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 240, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 123, 91));
        jLabel2.setText("Customer ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 123, 91));
        jLabel3.setText("Order Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 123, 91));
        jLabel4.setText("Amount:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));
        jPanel1.add(or_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 10));
        jPanel1.add(cId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     if (action.equals("Add")) {
        if (validateRegister() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields correctly!");
            return;
        }

        DBcon dbc = new DBcon();
        // Matching your schema: c_id, order_date, amount
        String query = "INSERT INTO tbl_orders (c_id, order_date, amount) "
                     + "VALUES ('" + cId.getValue() + "', '" + orderdate.getText() + "', '" + amount.getText() + "')";
        
        if (dbc.insertData(query) == 1) {
            JOptionPane.showMessageDialog(null, "Order Successfully Placed!");
            close();
        }

    } else if (action.equals("Update")) {
        if (validateRegister() == 0) return;

        DBcon dbc = new DBcon();
        // Matching your schema: c_id, order_date, amount
        String query = "UPDATE tbl_orders SET "
                     + "c_id = '" + cId.getValue() + "', "
                     + "order_date = '" + orderdate.getText() + "', "
                     + "amount = '" + amount.getText() + "' "
                     + "WHERE o_id = '" + or_id.getText() + "'";

        dbc.updateData(query);
        JOptionPane.showMessageDialog(null, "Order Updated Successfully!");
        close();
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void orderdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderdateActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JTextField amount;
    public javax.swing.JSpinner cId;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel or_id;
    public javax.swing.JTextField orderdate;
    public javax.swing.JLabel st_label;
    // End of variables declaration//GEN-END:variables
}
