/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.io.File;

/**
 *
 * @author Lester
 */
public class Order_details extends javax.swing.JFrame {

    /**
     * Creates new form Order_details
     */
 public Order_details() {
    initComponents();
    // Makes the background of the frame transparent for the rounded card effect
    this.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    // 1. Correct listener for the Quantity Spinner
    quan.addChangeListener(new javax.swing.event.ChangeListener() {
        @Override
        public void stateChanged(javax.swing.event.ChangeEvent e) {
            calculateSubtotal();
        }
    });
    
    // 2. Correct listener for the Product ID Spinner
    pid.addChangeListener(new javax.swing.event.ChangeListener() {
        @Override
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            // When Product ID changes, we recalculate to get the new price from the DB
            calculateSubtotal();
        }
    });
}
                public String destination = "";
    File selectedFile;
    public String oldpath;
    public String path;
    
int validateRegister() {
    try {
        // Updated: Use .getValue() for the quantity spinner
        int quantityValue = (int) quan.getValue();
        if(quantityValue <= 0 || subtotal.getText().equals("0.00")) {
            return 0;
        }
        if((int)pid.getValue() <= 0 || (int)oid.getValue() <= 0) {
            return 0;
        }
        return 1;
    } catch (Exception e) {
        return 0;
    }
}
  
private void calculateSubtotal() {
    try {
        config.DBcon dbc = new config.DBcon();
        int productID = (int) pid.getValue();
        
        java.sql.ResultSet rs = dbc.getData("SELECT p_price FROM tbl_products WHERE p_id = '" + productID + "'");
        
        if (rs.next()) {
            double price = rs.getDouble("p_price");
            // Updated: Use .getValue() and cast to Number/Integer for the spinner
            int quantity = (int) quan.getValue(); 
            double total = quantity * price;
            
            subtotal.setText(String.format("%.2f", total));
        } else {
            subtotal.setText("0.00");
        }
    } catch (Exception e) {
        subtotal.setText("0.00");
    }
}
  private void calculateWithPrice(double price) {
    try {
        // Updated: Use getValue() for JSpinner and cast to Number to get the double value
        double quantity = ((Number) quan.getValue()).doubleValue(); 
        double total = quantity * price;
        subtotal.setText(String.format("%.2f", total));
    } catch (Exception e) {
        // Handles cases where the spinner value might be null or invalid
        subtotal.setText("0.00");
    }
}
  
     public String action;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);
        st_label = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        oid = new javax.swing.JSpinner();
        pid = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quan = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(253, 245, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(166, 123, 91));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 30));

        jPanel4.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 210, 50));

        subtotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });
        jPanel4.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 40));
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, 10));
        jPanel4.add(oid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, -1));

        pid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pidStateChanged(evt);
            }
        });
        jPanel4.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 123, 91));
        jLabel2.setText("Product ID:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 123, 91));
        jLabel3.setText("Quantity:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 70, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 123, 91));
        jLabel4.setText("Subtotal:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(166, 123, 91));
        jLabel5.setText("Order ID:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        quan.setModel(new javax.swing.SpinnerNumberModel());
        jPanel4.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 550, 400));

        jPanel2.setBackground(new java.awt.Color(166, 123, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A67B5B.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 200, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffe.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
 if (action.equals("Add")) {
        if (validateRegister() == 1) {
            config.DBcon dbc = new config.DBcon();

            // Use .getValue() for oid, pid, and quan since they are JSpinners
            String sql = "INSERT INTO tbl_orderDetails (o_id, p_id, quantity, subtotal) "
                       + "VALUES ('" + oid.getValue() + "', '" 
                       + pid.getValue() + "', '" 
                       + quan.getValue() + "', '" 
                       + subtotal.getText() + "')";

            if (dbc.insertData(sql) == 1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Item Added to Order!");
                this.dispose();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Please fill in all fields correctly!");
        }

    } else if (action.equals("Update")) {
        if (validateRegister() == 1) { // Added validation for Update as well
            config.DBcon dbc = new config.DBcon();

            // Updated quan.getText() to quan.getValue()
            String sql = "UPDATE tbl_orderDetails SET "
                       + "o_id = '" + oid.getValue() + "', "
                       + "p_id = '" + pid.getValue() + "', "
                       + "quantity = '" + quan.getValue() + "', "
                       + "subtotal = '" + subtotal.getText() + "' "
                       + "WHERE order_details = '" + id.getText() + "'";

            dbc.updateData(sql);
            javax.swing.JOptionPane.showMessageDialog(null, "Details Updated!");
            this.dispose();
        } else {
             javax.swing.JOptionPane.showMessageDialog(null, "Invalid update data. Please check Quantity.");
        }
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void pidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pidStateChanged
      calculateSubtotal();
    }//GEN-LAST:event_pidStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JSpinner oid;
    public javax.swing.JSpinner pid;
    public javax.swing.JSpinner quan;
    public javax.swing.JLabel st_label;
    public javax.swing.JTextField subtotal;
    // End of variables declaration//GEN-END:variables
}
