/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Lester
 */
public class payments_form extends javax.swing.JFrame {

    /**
     * Creates new form payments_form
     */
    public payments_form() {
        initComponents();
    }

    int validateRegister() {
    if (amountpaid.getText().trim().isEmpty() || p_date.getText().trim().isEmpty()) {
        return 0;
    }
    try {
        // Ensure amount is actually a number since the DB expects a REAL
        Double.parseDouble(amountpaid.getText().trim());
        return 1;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid Amount format!");
        return 0;
    }
}
            public String destination = "";
    File selectedFile;
    public String oldpath;
    public String path;
     public String action;
     
     private boolean orderExists(int id) {
 
    config.DBcon dbc = new config.DBcon();
    try {
        // Query the orders table for the specific ID
        java.sql.ResultSet rs = dbc.getData("SELECT o_id FROM tbl_orders WHERE o_id = " + id);
        
        // If rs.next() is true, a record was found
        return rs.next(); 
    } catch (java.sql.SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
        return false;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);
        st_label = new javax.swing.JLabel();
        amountpaid = new javax.swing.JTextField();
        p_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        oId = new javax.swing.JSpinner();
        paymentMethod = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 245, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(166, 123, 91));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 30));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, 50));

        amountpaid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        amountpaid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        amountpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidActionPerformed(evt);
            }
        });
        jPanel1.add(amountpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 240, 30));

        p_date.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        p_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        p_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_dateActionPerformed(evt);
            }
        });
        jPanel1.add(p_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 123, 91));
        jLabel2.setText("Order ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 123, 91));
        jLabel3.setText("Payment Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 123, 91));
        jLabel4.setText("Payment Method:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));
        jPanel1.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 10));
        jPanel1.add(oId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        paymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "paycash", "gcash" }));
        jPanel1.add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(166, 123, 91));
        jLabel5.setText("Amount:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 370));

        jPanel2.setBackground(new java.awt.Color(166, 123, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A67B5B.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 200, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffe.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
      if (action.equals("Add")) {
        if (validateRegister() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields correctly!");
            return;
        }

        config.DBcon dbc = new config.DBcon();
        // Updated to match tbl_payment schema from image_0c5447.png
        String query = "INSERT INTO tbl_payment (o_id, payment_method, amount_paid, payment_date) "
                     + "VALUES ('" + oId.getValue() + "', "
                     + "'" + paymentMethod.getSelectedItem() + "', "
                     + "'" + amountpaid.getText() + "', "
                     + "'" + p_date.getText() + "')";

        if (dbc.insertData(query) == 1) {
            JOptionPane.showMessageDialog(null, "Payment Recorded Successfully!");
            this.dispose();
        }

    } else if (action.equals("Update")) {
        if (validateRegister() == 0) return;

        config.DBcon dbc = new config.DBcon();
        // Updated to match tbl_payment schema and use payment_id as the PK
        String query = "UPDATE tbl_payment SET "
                     + "o_id = '" + oId.getValue() + "', "
                     + "payment_method = '" + paymentMethod.getSelectedItem() + "', "
                     + "amount_paid = '" + amountpaid.getText() + "', "
                     + "payment_date = '" + p_date.getText() + "' "
                     + "WHERE payment_id = '" + p_id.getText() + "'";

        dbc.updateData(query);
        JOptionPane.showMessageDialog(null, "Payment Details Updated!");
        this.dispose();
    }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void amountpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountpaidActionPerformed

    private void p_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payments_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payments_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payments_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payments_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payments_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JTextField amountpaid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JSpinner oId;
    public javax.swing.JTextField p_date;
    public javax.swing.JLabel p_id;
    public javax.swing.JComboBox<String> paymentMethod;
    public javax.swing.JLabel st_label;
    // End of variables declaration//GEN-END:variables
}
