/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.DBcon;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Lester
 */
public class Productform extends javax.swing.JFrame {
private Products_form dashboard;

public Productform() {
    this(null); // This redirects to the constructor below
}

/**
 * Creates new form Productform
 */
public Productform(Products_form dashboard) {
    this.dashboard = dashboard; 
    initComponents();
    
    // 1. Handle Image Session Display
    try {
        displayImageIcon();
    } catch (Exception e) {
        System.out.println("Image Session not initialized yet: " + e.getMessage());
        image.setText("Click to Upload");
    }
        
    // 2. Set up Image Click Listeners
    java.awt.event.MouseAdapter imageClick = new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imageMouseClicked(evt);
        }
    };
    
    image.addMouseListener(imageClick);
    edit.addMouseListener(imageClick); // Both the circle and edit icon now trigger upload
}

        public String destination = "";
    File selectedFile;
    public String oldpath;
    public String path;
     public String action;
    // Helper to check if the file is already in your image folder
public int FileExistenceChecker(String path) {
    java.io.File file = new java.io.File(path);
    if (file.exists()) {
        return 1;
    } else {
        return 0;
    }
}

// Helper to scale the image so it fits perfectly inside your JLabel
public javax.swing.ImageIcon ResizeImage(String imgPath, byte[] pic, javax.swing.JLabel label) {
    javax.swing.ImageIcon myImage;
    if (imgPath != null) {
        myImage = new javax.swing.ImageIcon(imgPath);
    } else {
        myImage = new javax.swing.ImageIcon(pic);
    }
    
    java.awt.Image img = myImage.getImage();
    java.awt.Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), java.awt.Image.SCALE_SMOOTH);
    javax.swing.ImageIcon image = new javax.swing.ImageIcon(newImg);
    return image;
}

public void displayImageIcon() {
    // Add a null check for the session instance
    if (config.imageSession.getInstance() == null) {
        image.setText("Click to Upload");
        return;
    }
    
    String path = config.imageSession.getInstance().getImagePath();
    if (path != null && !path.isEmpty() && !path.equals("null")) {
        image.setIcon(ResizeImage(path, null, image));
        image.setText(""); 
    } else {
        image.setIcon(null); 
        image.setText("Click to Upload");
    }
}/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = add = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 5;
                int borderRadius = 20;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        add.setOpaque(false);
        st_label = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = jPanel9 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int shadowSize = 10;
                int borderRadius = 10;
                int width = getWidth() - shadowSize * 2;
                int height = getHeight() - shadowSize * 2;

                // 1. Draw the Shadow
                for (int i = 0; i < shadowSize; i++) {
                    // Gradually fade the black color to create a soft blur
                    g2.setColor(new java.awt.Color(0, 0, 0, (shadowSize - i) * 5)); 
                    g2.drawRoundRect(shadowSize - i, shadowSize - i, width + i * 2, height + i * 2, borderRadius, borderRadius);
                }

                // 2. Fill the Main Panel (White Card)
                g2.setColor(getBackground()); // Uses the color from the Design tab
                g2.fillRoundRect(shadowSize, shadowSize, width, height, borderRadius, borderRadius);

                g2.dispose();
            }
        };
        // This makes the area outside the rounded card transparent
        jPanel9.setOpaque(false);
        image = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Create the circular clip
                int diameter = Math.min(getWidth(), getHeight());
                int x = (getWidth() - diameter) / 2;
                int y = (getHeight() - diameter) / 2;

                java.awt.geom.Ellipse2D.Double circle = new java.awt.geom.Ellipse2D.Double(x, y, diameter, diameter);
                g2.setClip(circle);

                // Paint the image inside the circle
                super.paintComponent(g2);

                // Optional: Add a white border around the circle
                g2.setClip(null); // Remove clip to draw border on top
                g2.setColor(java.awt.Color.LIGHT_GRAY);
                g2.setStroke(new java.awt.BasicStroke(2));
                g2.draw(circle);

                g2.dispose();
            }
        };
        edit = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Create the circular clip
                int diameter = Math.min(getWidth(), getHeight());
                int x = (getWidth() - diameter) / 2;
                int y = (getHeight() - diameter) / 2;

                java.awt.geom.Ellipse2D.Double circle = new java.awt.geom.Ellipse2D.Double(x, y, diameter, diameter);
                g2.setClip(circle);

                // Paint the image inside the circle
                super.paintComponent(g2);

                // Optional: Add a white border around the circle
                g2.setClip(null); // Remove clip to draw border on top
                g2.setColor(java.awt.Color.LIGHT_GRAY);
                g2.setStroke(new java.awt.BasicStroke(2));
                g2.draw(circle);

                g2.dispose();
            }
        };
        id = new javax.swing.JLabel();
        stats = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 245, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(92, 50, 22));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        st_label.setForeground(new java.awt.Color(255, 255, 255));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 30));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 240, 50));

        desc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel1.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 240, 150));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(166, 123, 91));
        jLabel1.setText("Product Description:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        pname.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 30));

        category.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 30));

        price.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91), 2));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 123, 91));
        jLabel2.setText("Product Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 123, 91));
        jLabel3.setText("Category:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 123, 91));
        jLabel4.setText("Status:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 231, -1, 30));

        jPanel9.setBackground(new java.awt.Color(62, 39, 35));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });
        jPanel9.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jPanel9.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 30, 28));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 20));

        stats.setEditable(true);
        stats.setForeground(new java.awt.Color(166, 123, 91));
        stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Picked", "Regular" }));
        stats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 123, 91)));
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });
        jPanel1.add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(166, 123, 91));
        jLabel5.setText("Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 390));

        jPanel2.setBackground(new java.awt.Color(166, 123, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/A67B5B.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 200, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffe.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(211, 84, 0));
    }//GEN-LAST:event_addMousePressed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(243, 156, 18)) ;
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(255, 179, 71));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
 String currentStatus = stats.getSelectedItem().toString();
String currentCat = category.getText();
String currentId = id.getText();
DBcon dbc = new DBcon();

// --- START VALIDATION LOGIC ---
if (currentStatus.equals("Picked")) {
    try {
        // 1. Check Rule: Max 2 products per specific category
        // We count existing 'Picked' items in the SAME category, excluding the current ID if updating
        String countInCatQuery = "SELECT COUNT(*) FROM tbl_products WHERE p_status = 'Picked' "
                               + "AND category = '" + currentCat + "' AND p_id != '" + currentId + "'";
        java.sql.ResultSet rs1 = dbc.getData(countInCatQuery);
        
        if (rs1.next() && rs1.getInt(1) >= 2) {
            JOptionPane.showMessageDialog(null, "Limit Reached: Category '" + currentCat + "' already has 2 picked products.");
            return; 
        }

        // 2. Check Rule: Max 3 unique categories total
        // First, check if this specific category is already one of the "Picked" ones
        String checkThisCatQuery = "SELECT COUNT(*) FROM tbl_products WHERE p_status = 'Picked' AND category = '" + currentCat + "'";
        java.sql.ResultSet rsCheck = dbc.getData(checkThisCatQuery);
        
        boolean isCategoryAlreadyInUse = false;
        if (rsCheck.next() && rsCheck.getInt(1) > 0) {
            isCategoryAlreadyInUse = true;
        }

        // If this is a NEW category being marked as 'Picked', check if we already have 3 others
        if (!isCategoryAlreadyInUse) {
            String totalCatsQuery = "SELECT COUNT(DISTINCT category) FROM tbl_products WHERE p_status = 'Picked'";
            java.sql.ResultSet rs2 = dbc.getData(totalCatsQuery);
            if (rs2.next() && rs2.getInt(1) >= 3) {
                JOptionPane.showMessageDialog(null, "Limit Reached: You can only have a maximum of 3 unique categories marked as Picked.");
                return; 
            }
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Validation Error: " + e.getMessage());
    }
}
// --- END VALIDATION LOGIC ---

// EXECUTE DATABASE OPERATIONS
if (action.equals("Add")) {
    String sql = "INSERT INTO tbl_products (p_name, category, price, p_image, p_desc, p_status) "
        + "VALUES ('" + pname.getText() + "', '" + currentCat + "', '" + price.getText() + "', "
        + "'" + destination + "', '" + desc.getText() + "', '" + currentStatus + "')";

    if (dbc.insertData(sql) == 1) {
        JOptionPane.showMessageDialog(null, "Product Saved!");
        
        if (dashboard != null) {
            dashboard.loadProductsFromDB();
        }
        this.dispose();
    }
} else if (action.equals("Update")) {
    String query = "UPDATE tbl_products SET "
        + "p_name = '" + pname.getText() + "', "
        + "category = '" + currentCat + "', "
        + "price = '" + price.getText() + "', "
        + "p_image = '" + ((destination == null || destination.isEmpty()) ? oldpath : destination) + "', " 
        + "p_desc = '" + desc.getText() + "', "
        + "p_status = '" + currentStatus + "' "
        + "WHERE p_id = '" + currentId + "'";

    dbc.updateData(query);
    JOptionPane.showMessageDialog(null, "Product Updated Successfully!");
    
    if (dashboard != null) {
        dashboard.loadProductsFromDB();
    }
    this.dispose();
}
    }//GEN-LAST:event_addMouseClicked

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
     JFileChooser fileChooser = new JFileChooser();
    int returnValue = fileChooser.showOpenDialog(null);

    if (returnValue == JFileChooser.APPROVE_OPTION) {
        try {
            selectedFile = fileChooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            
            // It is safer to use the project path dynamically
            destination = "src/image/" + selectedFile.getName();

            if (FileExistenceChecker(destination) == 1) {
                JOptionPane.showMessageDialog(null, "File Already Exists!");
                destination = ""; 
            } else {
                // Update the UI immediately
                image.setIcon(ResizeImage(path, null, image));
                image.setText("");

                // Copy the file to your internal project folder
                java.nio.file.Path sourcePath = java.nio.file.Paths.get(path);
                java.nio.file.Path destPath = java.nio.file.Paths.get(destination);
                java.nio.file.Files.copy(sourcePath, destPath, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                
                System.out.println("Image successfully uploaded to: " + destination);
            }
        } catch (Exception ex) {
            System.out.println("File Upload Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_imageMouseClicked

    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JTextField category;
    public javax.swing.JTextField desc;
    private javax.swing.JLabel edit;
    public javax.swing.JLabel id;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTextField pname;
    public javax.swing.JTextField price;
    public javax.swing.JLabel st_label;
    public javax.swing.JComboBox<String> stats;
    // End of variables declaration//GEN-END:variables
}
